name: Push pipeline

on:
  push:
    branches: [ "main" ]
jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: davidbalko10/ip-app:${{ github.sha }}
      - name: Generate Trivy Vulnerability Report
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'davidbalko10/ip-app:${{ github.sha }}'
          output: trivy-report.json
          format: json
          exit-code: 0
          vuln-type: 'os,library'
      - name: Upload Vulnerability Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json
          retention-days: 30
      - name: Fail build on High/Criticial Vulnerabilities
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'davidbalko10/ip-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
  deploy:
    runs-on: self-hosted
    needs: build-and-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Helm lint
        run: |
          cd charts/ip-app-chart
          helm lint
      - name: Helm deploy
        run: |
          cd charts/ip-app-chart
          helm upgrade --set image.tag=${{ github.sha }} -n staging ip-app .
